version: "3.9"

services:
  telegram-gpt-bot:
    build: .
    volumes:
      - ./cfg/.env:/app/.env
      - ./cfg/session_name.session:/app/session_name.session
    tty: true
    stdin_open: true
    entrypoint: 
      - /bin/sh
      - -c
      - |
        rm -rf /app/repository
        git clone https://github.com/Nevenuga/telegram-gpt-bot.git /app/repository && \
        cd /app/repository && \
        pip install --no-cache-dir -r requirements.txt && \
        # Устанавливаем правильные права на файлы
        chmod 666 /app/.env && \
        chmod 666 /app/session_name.session && \
        tail -f /dev/null
        # python3 telegram_bot.py --env /app/.env --session /app/session_name.session
