version: "3.9"

services:
  telegram-gpt-bot:
    build: .
    volumes:
      - ./cfg:/app/cfg
    tty: true
    stdin_open: true
    entrypoint: 
      - /bin/sh
      - -c
      - |
        rm -rf /app/repository
        git clone https://github.com/Nevenuga/telegram-gpt-bot.git /app/repository && \
        cd /app/repository && \
        pip install --no-cache-dir -r requirements.txt && \
        tail -f /dev/null
        # python3 telegram_bot.py --env /app/cfg/.env --session /app/cfg/session_name.session
